---
title: DeLorean analysis of Trapnell et al. myoblast data
author: John Reid
bibliography: DeLorean.bib
output: html_document
---

<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{DeLorean analysis of Trapnell et al. myoblast data}
-->


```{r config, echo=FALSE, message=FALSE}
library(knitr)
library(knitcitations)
library(rmarkdown)
#
# knitr options
#
opts_chunk$set(
    fig.path = 'figures/Trapnell-',
    stop_on_error = TRUE,
    fig.width = 12.5,
    fig.height = 8)
#
# Citations
#
cleanbib()
cite_options(
    # hyperlink = 'to.doc',
    hyperlink = TRUE,
    # style = 'html',
    # citation_format = 'text',
    citation_format = "pandoc",
    cite.style = "numeric",
    check.entries = TRUE)
    # hyperlink = TRUE)
bib <- read.bibtex("DeLorean.bib")

```

```{r build, echo=FALSE, eval=FALSE}
library(devtools)
load_all('..')
render('DeLorean-McDavid.Rmd')

```

```{r loadLibs, echo=FALSE, message=FALSE}
# suppressMessages(loadfonts())
library(DeLorean)
#
# Stylesheet
#
options(markdown.HTML.stylesheet = system.file("inst/Rmd/foghorn.css",
                                               package="DeLorean"))

```


Load data.
```{r loadData, eval=FALSE}
library(DeLorean)
data(TrapnellDeLorean)

```

Summarise the meta-data.
```{r summariseMeta}
summary(trapnell.gene.meta)
summary(trapnell.cell.meta)

```

Examine data for empirical Bayes estimation of hyperparameters.
```{r empBayes}
dl <- de.lorean(
    trapnell.expr,
    trapnell.gene.meta,
    trapnell.cell.meta)
dl <- estimate.hyper(
    dl,
    sigma.tau=6,
    delta=.5)
# knit.report(dl, "hyper-parameters")

```

Select cells at random if we have too many.
```{r chooseCells}

set.seed(1)
max.cells <- 47
cells.sampled <- sample(trapnell.cell.meta$cell, max.cells)
cell.filter <- function(cells) cells %in% cells.sampled
dl <- filter.cells(dl, cell.filter)

```


Select genes by variance.
```{r chooseGenes}

max.genes <- 51
genes.high.var <- (trapnell.gene.meta
                   %>% arrange(-lpe.sd)
                   %>% head(max.genes))$gene
gene.filter <- function(genes) genes %in% genes.high.var
dl <- filter.genes(dl, gene.filter)

```


Define and compile the model, find the best initialisation, and fit the model.
```{r model}
dl <- format.for.stan(dl)
dl <- compile.model.simple(dl)
dl <- find.best.tau(dl)
dl <- fit.model(dl)
sort(sapply(dl, object.size))

```

Examine convergence.
```{r examConv}
dl <- examine.convergence(dl)
dl$rhat.sorted

```


Examine posterior.
```{r posterior}
dl <- process.posterior(dl)

#
# Analyse gene noise levels
#
dl <- analyse.noise.levels(dl)
# knit.report(dl, "posterior")

#
# Plot predictions from best sample
#
dl <- make.predictions(dl)
gp <- plot(dl, type="best.predictions")
print(gp)

```


R version and packages used:
```{r sessionInfo}
sessionInfo()

```

