### Cell sizes

The distribution of cell sizes by capture time.
```{r cellSizeByCapture}
ggplot(
    samples.l$S %>% left_join(cell.map, by = 'c'),
    aes(x=S, color=capture, fill=capture)) +
  geom_histogram(position = 'dodge', bins = 30) +
  geom_rug()
```

The posterior mean and standard deviation of the cell sizes coloured by capture group.
```{r cellSizeMeanSD}
S.l <-
  samples.l$S %>%
  group_by(c) %>%
  summarise(S.mean=mean(S), S.sd=sd(S))
ggplot(
    left_join(S.l, cell.map, by = 'c'),
    aes(x=S.mean, y=S.sd, color=capture)) +
  geom_point()
```

Correlations between cell size and pseudotime per capture time.
```{r tauS}
tau_S <- with(samples.l,
  tau %>%
    filter(iter == best.sample) %>%
    left_join(S, by = c('iter', 'c')) %>%
    left_join(cell.map, by = c("c", "cell", 'capture')))
tau_S %>%
  group_by(capture) %>%
  summarise(cor = cor(tau, S)) %>%
  knitr::kable()
```

Plot the relationship between pseudotime and cell size.
```{r plotTauS}
ggplot(tau_S, aes(x = tau, y = S, colour = capture)) + geom_point() +
  geom_smooth(method="lm", fill=NA)
```
