---
title: Monocle analysis of Windram et al. arabidopsis data
author: John Reid
bibliography: ../../vignettes/DeLorean.bib
output: html_document
---


```{r build, echo=FALSE, eval=FALSE}
library(devtools)
load_all('../..')
library(rmarkdown)
render('Windram-Monocle.Rmd')

```

```{r config, echo=FALSE, message=FALSE}
library(knitr)
library(knitcitations)
library(rmarkdown)
#
# knitr options
#
opts_chunk$set(
    fig.path = 'figures/Windram-',
    stop_on_error = TRUE,
    fig.width = 12.5,
    fig.height = 8)
#
# Citations
#
cleanbib()
cite_options(
    # hyperlink = 'to.doc',
    hyperlink = TRUE,
    # style = 'html',
    # citation_format = 'text',
    citation_format = "pandoc",
    cite.style = "numeric",
    check.entries = TRUE)
    # hyperlink = TRUE)
bib <- read.bibtex("../../vignettes/DeLorean.bib")
if (file.exists("config.R")) {
    source("config.R")
}
#
# Widths for saving figures
#
text.width <- 4.7  # LaTeX width in inches
golden.ratio <- 1.618  # Pleasing ratio
fig.width <- text.width
fig.height <- text.width / golden.ratio

```

```{r init, echo=FALSE, message=FALSE, warning=FALSE}
# suppressMessages(loadfonts())
library(DeLorean)
#
# Stylesheet
#
options(markdown.HTML.stylesheet = system.file("inst/Rmd/foghorn.css",
                                               package="DeLorean"))
font.family <- "Verdana"
font.theme <- theme_update(text=element_text(family=font.family))
theme_set(font.theme)

```


# Data

Load the data that we used for the DeLorean analysis and create a
`CellDataSet` for use with `Monocle`.
```{r loadLib}
library(monocle)
.data <- readRDS('Windram-input.rds')
colnames(.data$expr) <- rownames(.data$cell.meta) <- .data$cell.meta$cell
rownames(.data$expr) <- rownames(.data$gene.meta) <- .data$gene.meta$gene
cds <- new("CellDataSet",
           exprs=exp(.data$expr),
           phenoData=new("AnnotatedDataFrame",
                         data=as.data.frame(.data$cell.meta)),
           featureData=new("AnnotatedDataFrame",
                           data=as.data.frame(.data$gene.meta)))
cds@expressionFamily <- gaussianff()

```


## Check data is log normal

```{r logNormal}
# Log-transform each value in the expression matrix.
L <- log(exprs(cds))
# Standardize each gene, so that they are all on the same scale,
# Then melt the data with plyr so we can plot it easily"
melted_dens_df <- melt(t(scale(t(L))))
# Plot the distribution of the standardized gene expression values.
(
    qplot(value, geom = "density", data =melted_dens_df)
    + stat_function(fun=dnorm, size=0.5, color='red')
    # + xlab("Standardized log(FPKM)")
    + ylab("Density")
)

```


# Reduce dimension

```{r}
set.seed(37)
cds <- reduceDimension(cds, use_irlba=F)

```

# Order cells

```{r}
cds <- orderCells(cds, reverse=F)

```

Plot the spanning tree.
```{r}
gp.mst <- plot_spanning_tree(cds, color_by="capture")
print(gp.mst)
pdf('Windram-Monocle-order.pdf', width=fig.width, height=fig.height)
print(gp.mst)
dev.off()
png('Windram-Monocle-order.png', width=fig.width, height=fig.height,
    units="in", res=300)
print(gp.mst)
dev.off()

```

Plot some genes in pseudotime.
```{r}
genes.to.plot <- sample(rownames(fData(cds)), 3)
p <- plot_genes_in_pseudotime(cds[genes.to.plot,], color_by="capture")
print(p)
pdf('Windram-Monocle-pseudotime.pdf', width=fig.width, height=fig.height)
print(p)
dev.off()

```

Plot pseudotime against true capture time.
```{r}
.data <- as(phenoData(cds), "data.frame")
gp.monocle.pseudo <- (
    ggplot(.data,
           aes(x=Pseudotime,
               y=obstime.orig))
    + geom_point()
    + scale_x_continuous(name="pseudotime")
    + scale_y_continuous(name="capture time"))
print(gp.monocle.pseudo)
ggsave('Windram-Monocle-compare.pdf', gp.monocle.pseudo,
       width=text.width, height=text.width)
ggsave('Windram-Monocle-compare.png', gp.monocle.pseudo,
       width=fig.width, height=fig.height, units="in", dpi=300)
# What is the correlation?
with(.data, cor(obstime.orig, Pseudotime, method="spearman"))

```


R version and packages used:
```{r Rversion}
sessionInfo()
```
